dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

os:
  - linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: test
      script:
        - cd projects/tcon-22/select-country && ../../../node_modules/.bin/jest --coverage

after_success:
  - codecov

cache:
  directories:
    - node_modules # NPM packages
